import React from 'react';
import Canvas from './Canvas';
import NoteCanvas from './NoteCanvas';

import '../css/PianoRoll.css';

/**
 * Displays the song and his information.
 * For example showing his length and name.
 * @param holder
 * @returns
 */
const Pianoroll = function pianoroll(holder: { phase: number, inputDevice: any }) {
  return (
    <div id="core" className="core">
      <div id="gameBox" className="gameBox">
        <div>
          <Canvas
            className="whiteLine"
            position="93%"
          />
          <NoteCanvas
            id="w1"
            className="white"
            keyboard="q"
            specificNote="C3"
            position="93%"
            phase={holder.phase}
            inputDevice={holder.inputDevice}
          />
        </div>
        <div>
          <Canvas
            className="whiteLine"
            position="78.5%"
          />
          <NoteCanvas
            id="w2"
            className="white"
            keyboard="w"
            specificNote="D3"
            position="78.5%"
            phase={holder.phase}
            inputDevice={holder.inputDevice}
          />
        </div>
        <div>
          <Canvas
            className="whiteLine"
            position="64%"
          />
          <NoteCanvas
            id="w3"
            className="white"
            keyboard="e"
            specificNote="E3"
            position="64%"
            phase={holder.phase}
            inputDevice={holder.inputDevice}
          />
        </div>
        <div>
          <Canvas
            className="whiteLine"
            position="50%"
          />
          <NoteCanvas
            id="w4"
            className="white"
            keyboard="r"
            specificNote="F3"
            position="50%"
            phase={holder.phase}
            inputDevice={holder.inputDevice}
          />
        </div>
        <div>
          <Canvas
            className="whiteLine"
            position="35.5%"
          />
          <NoteCanvas
            id="w5"
            className="white"
            keyboard="t"
            specificNote="G3"
            position="35.5%"
            phase={holder.phase}
            inputDevice={holder.inputDevice}
          />
        </div>
        <div>
          <Canvas
            className="whiteLine"
            position="21.5%"
          />
          <NoteCanvas
            id="w6"
            className="white"
            keyboard="z"
            specificNote="A3"
            position="21.5%"
            phase={holder.phase}
            inputDevice={holder.inputDevice}
          />
        </div>
        <div>
          <Canvas
            className="whiteLine"
            position="7%"
          />
          <NoteCanvas
            id="w7"
            className="white"
            keyboard="u"
            specificNote="B3"
            position="7%"
            phase={holder.phase}
            inputDevice={holder.inputDevice}
          />
        </div>

        <div>
          <Canvas
            className="blackLine"
            position="85.6%"
          />
          <NoteCanvas
            id="b1"
            className="black"
            keyboard="1"
            specificNote="C#3"
            position="85.6%"
            phase={holder.phase}
            inputDevice={holder.inputDevice}
          />
        </div>
        <div>
          <Canvas
            className="blackLine"
            position="71.5%"
          />
          <NoteCanvas
            id="b2"
            className="black"
            keyboard="2"
            specificNote="D#3"
            position="71.5%"
            phase={holder.phase}
            inputDevice={holder.inputDevice}
          />
        </div>
        <div>
          <Canvas
            className="blackLine"
            position="42.8%"
          />
          <NoteCanvas
            id="b3"
            className="black"
            keyboard="3"
            specificNote="F#3"
            position="42.8%"
            phase={holder.phase}
            inputDevice={holder.inputDevice}
          />
        </div>
        <div>
          <Canvas
            className="blackLine"
            position="28.5%"
          />
          <NoteCanvas
            id="b4"
            className="black"
            keyboard="4"
            specificNote="G#3"
            position="28.5%"
            phase={holder.phase}
            inputDevice={holder.inputDevice}
          />
        </div>
        <div>
          <Canvas
            className="blackLine"
            position="14.5%"
          />
          <NoteCanvas
            id="b5"
            className="black"
            keyboard="5"
            specificNote="A#3"
            position="14.5%"
            phase={holder.phase}
            inputDevice={holder.inputDevice}
          />
        </div>

        <div>
          <Canvas
            className="blackLine"
            position="-14.5%"
          />
          <NoteCanvas
            id="b6"
            className="black"
            keyboard="6"
            specificNote="C#4"
            position="-14.5%"
            phase={holder.phase}
            inputDevice={holder.inputDevice}
          />
        </div>
        <div>
          <Canvas
            className="blackLine"
            position="-28.5%"
          />
          <NoteCanvas
            id="b7"
            className="black"
            keyboard="7"
            specificNote="D#4"
            position="-28.5%"
            phase={holder.phase}
            inputDevice={holder.inputDevice}
          />
        </div>
        <div>
          <Canvas
            className="blackLine"
            position="-57.3%"
          />
          <NoteCanvas
            id="b8"
            className="black"
            keyboard="8"
            specificNote="F#4"
            position="-57.3%"
            phase={holder.phase}
            inputDevice={holder.inputDevice}
          />
        </div>
        <div>
          <Canvas
            className="blackLine"
            position="-71%"
          />
          <NoteCanvas
            id="b9"
            className="black"
            keyboard="9"
            specificNote="G#4"
            position="-71%"
            phase={holder.phase}
            inputDevice={holder.inputDevice}
          />
        </div>
        <div>
          <Canvas
            className="blackLine"
            position="-85.8%"
          />
          <NoteCanvas
            id="b10"
            className="black"
            keyboard="0"
            specificNote="A#4"
            position="-85.8%"
            phase={holder.phase}
            inputDevice={holder.inputDevice}
          />
        </div>

        <div>
          <Canvas
            className="whiteLine"
            position="-7%"
          />
          <NoteCanvas
            id="w8"
            className="white"
            keyboard="a"
            specificNote="C4"
            position="-7%"
            phase={holder.phase}
            inputDevice={holder.inputDevice}
          />
        </div>
        <div>
          <Canvas
            className="whiteLine"
            position="-21.5%"
          />
          <NoteCanvas
            id="w9"
            className="white"
            keyboard="s"
            specificNote="D4"
            position="-21.5%"
            phase={holder.phase}
            inputDevice={holder.inputDevice}
          />
        </div>
        <div>
          <Canvas
            className="whiteLine"
            position="-35.5%"
          />
          <NoteCanvas
            id="w10"
            className="white"
            keyboard="d"
            specificNote="E4"
            position="-35.5%"
            phase={holder.phase}
            inputDevice={holder.inputDevice}
          />
        </div>
        <div>
          <Canvas
            className="whiteLine"
            position="-50%"
          />
          <NoteCanvas
            id="w11"
            className="white"
            keyboard="f"
            specificNote="F4"
            position="-50%"
            phase={holder.phase}
            inputDevice={holder.inputDevice}
          />
        </div>
        <div>
          <Canvas
            className="whiteLine"
            position="-64%"
          />
          <NoteCanvas
            id="w12"
            className="white"
            keyboard="g"
            specificNote="G4"
            position="-64%"
            phase={holder.phase}
            inputDevice={holder.inputDevice}
          />
        </div>
        <div>
          <Canvas
            className="whiteLine"
            position="-78.5%"
          />
          <NoteCanvas
            id="w13"
            className="white"
            keyboard="h"
            specificNote="A4"
            position="-78.5%"
            phase={holder.phase}
            inputDevice={holder.inputDevice}
          />
        </div>
        <div>
          <Canvas
            className="whiteLine"
            position="-93%"
          />
          <NoteCanvas
            id="w14"
            className="white"
            keyboard="j"
            specificNote="B4"
            position="-93%"
            phase={holder.phase}
            inputDevice={holder.inputDevice}
          />
        </div>
      </div>
    </div>
  );
};

export { Pianoroll };
